version: '3'

services:

  db:
    image: postgres
    environment:
      - POSTGRES_DB=sunbot_db
      - POSTGRES_USER=sunbot
      - POSTGRES_PASSWORD=sunbot
    volumes:
      # Mounting a database in the host system so it's
      # persistent through different containers
      - ${HOME}/postgres-data/:/var/lib/postgresql/data
    env_file:
      - ./.env.db

  api:
    image: api
    build: sunbot-api/.
    command: gunicorn sunbotapi.wsgi:application --bind 0.0.0.0:8080 --access-logfile -
    #command: python manage.py runserver 0.0.0.0:8080
    #volumes:
    #  - ./sunbot-api:/code
    expose:
      - 8080
    env_file:
      - ./.env.api
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - api
      
  bot:
    image: bot
    build: sunbot-bot/.
    command: python main.py
    volumes:
      - ./sunbot-bot:/code
    env_file:
      - ./.env.bot
    depends_on:
      - api