# Generated by Django 3.0.8 on 2020-07-13 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('steam', models.URLField(blank=True, max_length=80, null=True)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('ign_warframe_pc', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.BigIntegerField()),
                ('channel_id', models.BigIntegerField()),
                ('period', models.DateField()),
                ('postcount', models.IntegerField(default=0)),
                ('attachments', models.IntegerField(default=0)),
                ('words', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.User')),
            ],
            options={
                'db_table': 'messages',
                'unique_together': {('server_id', 'channel_id', 'user_id', 'period')},
            },
        ),
    ]
