# Generated by Django 3.0.8 on 2020-07-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ign_ddo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ign_warframe_pc',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
