# Generated by Django 3.0.8 on 2020-07-14 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200714_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='server_id',
            new_name='guild_id',
        ),
        migrations.AlterUniqueTogether(
            name='messages',
            unique_together={('guild_id', 'channel_id', 'user_id', 'period')},
        ),
    ]
